Repository FillydelphiaDev/FillydelphiaPrototype, pull requests merged in 2020-04, with the labels that each got.

#12 Turn TraitModifiers into EventDispatcher
  Docs/Features/Character/TraitModifiers.md
  Docs/Features/Utils/EventDispatcher.md
  Game/Assets/Scripts/Character/Character.cs
  Game/Assets/Scripts/Character/CharacterMovement.cs
  Game/Assets/Scripts/Character/Trait.meta
  Game/Assets/Scripts/Character/Trait/Trait.cs
  Game/Assets/Scripts/Character/Trait/Trait.cs.meta
  Game/Assets/Scripts/Character/Trait/TraitModifiers.cs
  Game/Assets/Scripts/Utils/EventDispatcher.cs
  Game/Assets/Scripts/Utils/EventDispatcher.cs.meta
Labels: enhancement, scripting

#15 Remove view zone from CameraController
  Docs/Features/Controls/Camera.md
  Game/Assets/Prefabs/CameraRoot.prefab
  Game/Assets/Scenes/DemoScene.unity
  Game/Assets/Scripts/Player/CameraController.cs
Labels: enhancement, medium, scripting

#20 Simplify code (+ unify Walking and Running)
  Docs/Features/Character/Character.md
  Docs/Features/Utils/EventDispatcher.md
  Docs/Features/Utils/LevelZone.md
  Docs/GuidelinesCode.md
  Game/Assets/Scripts/Character/Character.cs
  Game/Assets/Scripts/Character/CharacterMovement.cs
  Game/Assets/Scripts/Player/CameraController.cs
  Game/Assets/Scripts/Player/MovementController.cs
  Game/Assets/Scripts/Utils/Editor/LevelZoneEditor.cs
  Game/Assets/Scripts/Utils/Editor/LevelZoneEditor.cs.meta
  Game/Assets/Scripts/Utils/EventDispatcher.cs
  Game/Assets/Scripts/Utils/EventDispatcher.cs.meta
  Game/Assets/Scripts/Utils/GeometryUtils.cs
  Game/Assets/Scripts/Utils/LevelZone.cs
  Game/Assets/Scripts/Utils/LevelZone.cs.meta
Labels: enhancement, major, scripting

#16 Stable 55 Utility draft
  Docs/Concepts/Locations/Utility&Entrance - cropped.png
  Docs/Concepts/Locations/Utility&Entrance.psd
  Docs/GuidelinesLevelDesign.md
  Game/Assets/Libraries/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Game/Assets/Materials/Debug/SolidBlack.mat
  Game/Assets/Materials/Debug/SolidBlack.mat.meta
  Game/Assets/Materials/Debug/SolidBlackUnlit.mat
  Game/Assets/Materials/Debug/SolidBlackUnlit.mat.meta
  Game/Assets/Materials/Debug/SolidLightGray.mat
  Game/Assets/Materials/Debug/SolidLightGray.mat.meta
  Game/Assets/Materials/Debug/SolidWhite.mat
  Game/Assets/Materials/Debug/SolidWhite.mat.meta
  Game/Assets/Materials/Debug/SolidYellow.mat
  Game/Assets/Materials/Debug/SolidYellow.mat.meta
  Game/Assets/Scenes/Draft.meta
  Game/Assets/Scenes/Draft/Stable55Utility.unity
  Game/Assets/Scenes/Draft/Stable55Utility.unity.meta
  Game/Assets/Scenes/Grayboxes/Stable55Utility.unity
Labels: feature, level-design, major

#29 Cutiemark shader
  Game/Assets/Materials/Characters/Pony/Canon/LightningDust/Body.mat
  Game/Assets/Materials/Characters/Pony/Canon/Noi/Body.mat
  Game/Assets/Materials/Characters/Pony/Canon/Vinyl/Body.mat
  Game/Assets/Materials/Characters/Pony/Debug/DebuggyValve/Body.mat
  Game/Assets/Materials/Characters/Pony/Debug/DebuggyValve/Horn.mat
  Game/Assets/Models/Characters/Pony/FemaleBody.fbx
  Game/Assets/Models/Characters/Pony/Horns/Horn.fbx
  Game/Assets/Presets.meta
  Game/Assets/Presets/Textures/Cutiemark.preset
  Game/Assets/Presets/Textures/Cutiemark.preset.meta
  Game/Assets/Shaders/Characters/Pony/PonyBody.shadergraph
  Game/Assets/Shaders/Characters/Pony/PonyBody.shadergraph.meta
  Game/Assets/Shaders/Characters/Pony/PonyBodyCutiemark.shadersubgraph
  Game/Assets/Shaders/Characters/Pony/PonyBodyCutiemark.shadersubgraph.meta
  Game/Assets/Textures/Characters/Pony/Cutiemarks.meta
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon.meta
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/LightningDust.png
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/LightningDust.png.meta
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/Noi.png
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/Noi.png.meta
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/RainbowDash.png
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/RainbowDash.png.meta
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/Vinyl.png
  Game/Assets/Textures/Characters/Pony/Cutiemarks/Canon/Vinyl.png.meta
  Raw/3D/Characters/Pony/FemaleBody-Cutiemark-Positions.txt
  Raw/3D/Characters/Pony/FemaleBody.blend
  Raw/3D/Characters/Pony/Horns/Horn.blend
Labels: feature, minor, scripting, shaders
